### ISSUE TITLE
Project scope

### ISSUE THREAD

**Issue by zmarouf** [brendanjryan/ccheck#1]
Hello! I saw your project on Reddit and I'm wondering what's the difference with https://github.com/instrumenta/conftest?

For now, my initial understanding was that this project seemed 100% laser focused on Kubernetes but you say the opposite in the Readme.

The syntactic sugar to display warning/error messages is a nice touch.
Could you elaborate on the vision and name as well as your plans moving forward? :)

Thank you

**Comment by brendanjryan** [comment]
@zmarouf great question - thanks for asking! 

This project is intended to be _strictly_ kubernetes focused, although in its minimal implementation there is likely a lot of overlap at the moment. I'll update the `README` to add more clarity. 

Noticing that there are a lot of overlaps between this repo and `conftest` i'll likely make contributions over there are well!
